# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cdd770602edda053dff080db472775c5ecab124e79da5a1f8f67a324f59a6ae5b082f526f7e09838c97a921f82e85fcf31523d6a866d77cbafd627167958171c

test:
  secret_key_base: def41cbd78867cc01d80e60dbf2d948c4530321f2aa02211244df74e2d2f64be3a6a31069fff436e6384913ad4d9a7774d0cea5348cd46a7a8d475e3412bd027

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
